### ISSUE TITLE
Condor job requirements specification quite limited

### ISSUE THREAD

**Issue by schuhschuh** [openmole/gridscale#5]
The current implementation of the CondorJobDescription only allows the specification of (case-sensitive) equality requirements. No other comparison operators are allowed. Moreover, all specified requirement 2-tuples are combined with a logical AND (```&&```). Even the most common requirement specifications are not possible, such as the minimum amount of memory or major OS version. I suggest allowing the user to specify each requirement as string as it would be given in the Condor submit script. The user will have to take care about the quoting in this case if necessary. Such requirement string can then also contain OR (```||```) operators. The list of strings is then again combined using an AND between individual requirement specifications and parentheses such that the OR always takes precedence, e.g.,

```
val requirements = List("Arch == X86_64", "OpSysMajorVer == 12 || OpSysMajorVer == 13", "Memory >= 4096")
```
results in the Condor job script entry
```
requirements = (Arch == X86_64) && (OpSysMajorVer == 12 || OpSysMajorVer == 13) && (Memory >= 4096)
```

**Comment by schuhschuh** [comment]
An example of a user quoted requirement value would be:
```scala
val requirements = List("""CondorRequirement == "Value with spaces" """)
```

**Comment by schuhschuh** [comment]
P.S.: The memory requirement is handled differently by GridScala using the special ```requested_memory``` option. Still, the current CondorRequirement list is too limited to be of much use.

**Comment by schuhschuh** [comment]
I guess I would revert this change: https://github.com/openmole/gridscale/commit/2ff4b4c7f555927fda98ee6c0fbc86c9b6919c65

**Comment by romainreuillon** [comment]
The best way to go, would be to keep the typed version and model the requirements further avoiding the systematic use of ==. To class OperatorName and Operator would do the thick. The application of operators such as >(value: String) to an OperatorName would create an Operator and Operator could be combined using &&, ||.... Also a constructor in the companion object of Operator would allow to construct an operator from a string.

**Comment by schuhschuh** [comment]
Hm, not as easy to use then from a configuration file, though. In my OpenMOLE plugin, I have an entry for the Condor environment requirements, where I would specify them just the same way as in a Condor submit script. If OpenMOLE/GridScale does it this way, I have to parse that string myself just so it is assembled to a string again. I understand that you want to check the validity of the syntax, but maybe this could be done by simply checking the syntax of the final string via a parser without the need for special types?

**Comment by romainreuillon** [comment]
You could use Operator(value: String) to generate a operator, no need to parse. Also there will be an implicit conversion from string -> Operator.

**Comment by romainreuillon** [comment]
BTW Operator should be called requirement.

**Comment by schuhschuh** [comment]
I assume I would still need to split the string at least at the OR operators for the implicit conversion to work ? Such as:

```scala
val requirements = List("Arch == X86_64", "OpSysMajorVer == 12 || OpSysMajorVer == 13", "Memory >= 4096")
requirements.flatMap(_.split("||").map(CondorRequirement(_))
```

Would this work with what you have in mind?

**Comment by schuhschuh** [comment]
But then I have a problem with precedence of AND and OR operators.... then you also need to model the whole not just as a list, but a tree...

**Comment by schuhschuh** [comment]
IMHO That's unnecessarily complicated and the requirements specification is anyway specific to the particular environment. You will have difficulties to come up with a unified description language for all supported environments.

**Comment by romainreuillon** [comment]
I don't think so because:
CondorRequirement || CondorRequirement would produce a CondorRequirement containing the requirement string and so on for every operator. So you could call directly :
```CondorRequirement("Arch == X86_64 && (OpSysMajorVer == 12 || OpSysMajorVer == 13))")```

If you need to.

This modeling would be specific to the condor env, and will guide the user in the requirement specification. No need for a cross environment genericity.... The requirement should be called CondorRequirement(....)

**Comment by schuhschuh** [comment]
Alright, if I can just pass the whole string and you split it up into the different operators and sub-requirements, I am fine with it.

**Comment by schuhschuh** [comment]
Seems there is a bug in the current implementation anyway. It produces:
```
requirements = ( OpSysShortName == "Ubuntu"&&OpSysMajorVer == "14" )
```
I figured that the problem are the quotes around the OpSysMajorVer. I tested it by copying the condor submit script and modifying it manually. After that the job run fine.

Also, following the example given in the condor_submit documentation, I would also rather go for parentheses around each AND part instead of the whole string.
```
requirements = ( OpSysShortName == "Ubuntu" ) && ( OpSysMajorVer == 14 )
```

**Comment by jopasserat** [comment]
What about that ca5c895a2249e80b6c707a05827cadbaa39aa058?

**Comment by romainreuillon** [comment]
Works for me.

What would also be great at some point is to have scala variables for standard requirement names, so the user can't make a spelling error if he uses them.

**Comment by jopasserat** [comment]
Yup, something generic across the environments for memory, cores, ... and all the rest that is common to all the environments.
